### ISSUE TITLE
With jest testing, thows     SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by pvaskria** [sators/react-password-checklist#15]
<img width="583" alt="Screenshot 2021-11-12 at 4 39 14 PM" src="https://user-images.githubusercontent.com/90251635/141457762-c3625368-e1e8-4d36-a299-6f1000ade77e.png">

Try with jest and it throws this error.

**Comment by sators** [comment]
@pvaskria This doesn't appear to be an issue with the library, but a Babel configuration error with your Jest environment.

See: https://stackoverflow.com/a/64223627/659188

**Comment by mustafasavul** [comment]
I am using Next.js and my easiest solution was to import [Next/Dynamic](https://nextjs.org/docs/advanced-features/dynamic-import).

Since Next.js is SSR-based, such a solution was created, as it might be trying to catch the later element.

const PasswordChecklist= dynamic(() => import("react-password-checklist"));

       <PasswordChecklist
                  rules={["minLength", "specialChar", "number", "capital", "match"]}
                  minLength={8}
                  value={formData.password}
                  valueAgain={formData.confirmPassword}
                  onChange={() => { }}
                />
